version: '3'
services:
# Data base container
  mysql_database:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=1234
    volumes:
      - mysql:/var/lib/mysql 
  # Wordpress container
  wordpress:
    depends_on:
      - mysql_database
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      - WORDPRESS_DB_HOST= mysql_database:3306
      - WORDPRESS_DB_USER=wp_user
      - WORDPRESS_DB_PASSWORD=1234
      - WORDPRESS_DB_NAME=wp_db
    volumes:
      - ./:/var/www/html
  php:
    depends_on:
      - mysql_database
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql_database
      - MYSQL_ROOT_PASSWORD=root

volumes:
  mysql: {}


